services:

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tattoo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tattoo_network

networks:
  tattoo_network:
    driver: bridge

volumes:
  postgres-data: